title: Pablo Github
email: pablo2@uni-bremen.de
description: >- # this means to ignore newlines until "baseurl:"
  Here you can find some old stuff which I did in my university, amateur projects to learn a new skill, journal about learning and much more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username: pfs-db
linkedin_username: pablo-freitas-it
# Build settings
theme: minima
plugins:
  - jekyll-feed
header_pages:
  - about.md
